sudo: required

language: c#

services:
- docker

env:
  - TEST_SUITE=Unit
  - TEST_SUITE=Integration

script:
- docker pull compulsivecoder/ubuntu-mono-ipfs
- curl https://raw.githubusercontent.com/CompulsiveCoder/ipfs-cs/$TRAVIS_BRANCH/test-from-github-via-docker.sh | sh -s $TRAVIS_BRANCH $TEST_SUITE
