sudo: required

language: c#

services:
- docker

env:
  - TEST_SUITE=Unit
  - TEST_SUITE=Integration

script:
- docker pull compulsivecoder/ubuntu-mono-ipfs
- sh test-via-docker.sh | sh -s $TRAVIS_BRANCH $TEST_SUITE

